package com.byr.myselfdemo.mapper.mysql_mapper;

import com.byr.myselfdemo.entity.SaasHouse;
import com.byr.myselfdemo.entity.SaasHouseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaasHouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_house
     *
     * @mbg.generated Fri Sep 06 15:29:41 CST 2019
     */
    long countByExample(SaasHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_house
     *
     * @mbg.generated Fri Sep 06 15:29:41 CST 2019
     */
    int deleteByExample(SaasHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_house
     *
     * @mbg.generated Fri Sep 06 15:29:41 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_house
     *
     * @mbg.generated Fri Sep 06 15:29:41 CST 2019
     */
    int insert(SaasHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_house
     *
     * @mbg.generated Fri Sep 06 15:29:41 CST 2019
     */
    int insertSelective(SaasHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_house
     *
     * @mbg.generated Fri Sep 06 15:29:41 CST 2019
     */
    List<SaasHouse> selectByExample(SaasHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_house
     *
     * @mbg.generated Fri Sep 06 15:29:41 CST 2019
     */
    SaasHouse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_house
     *
     * @mbg.generated Fri Sep 06 15:29:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") SaasHouse record, @Param("example") SaasHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_house
     *
     * @mbg.generated Fri Sep 06 15:29:41 CST 2019
     */
    int updateByExample(@Param("record") SaasHouse record, @Param("example") SaasHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_house
     *
     * @mbg.generated Fri Sep 06 15:29:41 CST 2019
     */
    int updateByPrimaryKeySelective(SaasHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_house
     *
     * @mbg.generated Fri Sep 06 15:29:41 CST 2019
     */
    int updateByPrimaryKey(SaasHouse record);
}