package com.gitee.taven.testdemo.entity.system;

import lombok.Data;
import org.springframework.web.util.pattern.PathPattern;

@Data
public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order.id
     *
     * @mbg.generated Thu Sep 05 14:54:58 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order.order_code
     *
     * @mbg.generated Thu Sep 05 14:54:58 CST 2019
     */
    private String orderCode;
    private String username;
    private String password;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order.order_name
     *
     * @mbg.generated Thu Sep 05 14:54:58 CST 2019
     */
    private String orderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order.order_count
     *
     * @mbg.generated Thu Sep 05 14:54:58 CST 2019
     */
    private Integer orderCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order.commodityId
     *
     * @mbg.generated Thu Sep 05 14:54:58 CST 2019
     */
    private Integer commodityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order.id
     *
     * @return the value of public.order.id
     *
     * @mbg.generated Thu Sep 05 14:54:58 CST 2019
     */
}