package com.gitee.taven.testdemo.entity.business;

import lombok.Data;

@Data
public class UserInformations {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_informations.id
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_informations.userid
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_informations.email
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_informations.address
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    private String address;

}